### PR TITLE
BCLOUD - 731 - Add friend from platform

### PR DESCRIPTION
**Pull request by francobithead**
Blueprint to test new api call: 

AddFriendFromPlatform - Test

### CODE REVIEW

**Comment by davidstl** [comment]
Hum so I'm wondering if we should have added an Enum for ADD/SYNC also... Make sure "ADD" is the default. Is that possible in blueprint?

**Review by davidstl — APPROVED** [review]

**Comment by francobithead** [comment]
> Hum so I'm wondering if we should have added an Enum for ADD/SYNC also... Make sure "ADD" is the default. Is that possible in blueprint?

Yes this is possible if I make it into a Enum then it would have a drop down menu and the first enum is defaulted.

**Comment by davidstl** [comment]
> > Hum so I'm wondering if we should have added an Enum for ADD/SYNC also... Make sure "ADD" is the default. Is that possible in blueprint?
> 
> Yes this is possible if I make it into a Enum then it would have a drop down menu and the first enum is defaulted.

I've used string for all other languages too... lets leave it. there is the javadoc right above it that gives you the 2 options anyway. Just making sure, for blueprint, can it auto-fill with ADD ?

**Comment by francobithead** [comment]
> 
> 
> > > Hum so I'm wondering if we should have added an Enum for ADD/SYNC also... Make sure "ADD" is the default. Is that possible in blueprint?
> > 
> > 
> > Yes this is possible if I make it into a Enum then it would have a drop down menu and the first enum is defaulted.
> 
> I've used string for all other languages too... lets leave it. there is the javadoc right above it that gives you the 2 options anyway. Just making sure, for blueprint, can it auto-fill with ADD ?

It's not auto-filled but it does have a default string value of ADD within the blueprint.

**Pull request merged**
